# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6c3e645a793a9be5954c634ea96b0662e8e589793d0be75b2f3808171b94c3762d7c94b5bc87fe318e41cb685af7d7012ab3ed00344087f6904f12115a231e3

test:
  secret_key_base: a7e9f8ccda0604f8291fb7c3f6b62506614881b94f1e4f5502b69414c72c22888c72998498884471e9b836a9118f5b9142107389d0b6f67fd3c9f9eb3bf8c89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
